### ISSUE TITLE
Can tab copy be done using only one click?

### ISSUE THREAD

**Issue by Agriek** [hansifer/tab-copy#10]
After upgrading Tab Copy, I can't copy the title and URL using just one click as before. Cancelling "keep format selector expanded", "show context menu", "Ignore pinned tabs", etc. don't help. Double click are still needed to copy.

Just wanted to use tab copy as convenient as possible. Appreciate a lot for the work you have done!

**Comment by hansifer** [comment]
If you're looking for a simple one-click tool, Tab Copy is probably overkill since it's optimized for workflow versatility.

If speed and convenience is your priority, nothing beats keyboard shortcuts. v4 delivers improvements on that front.

Check out the release notes for improvements and an explanation of why simple mode was retired: https://tabcopy.com/releases/4-0-0/

**Comment by hansifer** [comment]
Re-opening after some consideration.

A "One-click copy" option will be made available that applies the default tab range and format (configurable in [options](https://tabcopy.com/docs/options)).

This work is now in progress.

See: [One-click copy](https://tabcopy.com/roadmap#one-click-copy)

**Comment by hansifer** [comment]
This has been released.

[v4.1.0](https://tabcopy.com/releases/4-1-0)

**Comment by Agriek** [comment]
Thank you soooo much!! This one-tab copy mode helps a lot!
